[package]
name = "openquire"
version = "1.0.0"
description = "OpenQuire, an open source PDF suite"
license = "AGPL-3.0-or-later"
edition = "2021"

[lib]
name = "openquire_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
percent-encoding = "2"
cryptoki = "0.12"
serde = { version = "1", features = ["derive"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
